### ISSUE TITLE
Error when installing plugin on IOS

### ISSUE THREAD

**Issue by dinhtran16** [GeeTeam/gt3_flutter_plugin#1]
I get this error when I install the plugin and try to run it in the IOS simulator.

Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:41909D12-B142-4CEB-8923-010A1B2907DC, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:59DC6A9A-36BD-4F29-8691-C4CAA43F0D39, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:E6CF0411-298B-4D99-A69B-972B2BCE686A, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:5849AE0D-3836-41F3-A3DF-95B69F29903D, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:068FDFFC-5EE6-48B0-A5DC-FEA9D74667D6, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:63AA73FC-1625-4BD2-AB58-4E917FEB6A2B, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:35926CD3-4F20-44E0-BA8F-93CB771A67A7, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:00B481F3-71B1-4E6D-9FA1-8FB2A3C9C1C7, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:40919AF3-81BA-4CAC-8677-FB0FFC7969A6, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:CF3BCABB-9B15-47BF-9995-DF23228848F9, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:F544D46C-6D9F-4CAC-9249-12F0E8C62D7C, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:BA113F67-8A81-4494-A6FE-14CBE1AE690F, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:A553CFC5-C1E0-416F-9AFD-1E9DDE77B44A, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:8E2AF370-AC07-4472-BEAB-A12F301C1BC8, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:F50DDFE3-3444-4C9B-9C26-A625EB702228, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:0A27D652-A53B-4EF9-B998-8C438314D45C, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:A96C29F5-7789-46AD-825C-C95359366E1A, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:E20CD60B-56C4-4B57-9E7F-BDD7E4720E2D, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:E5EFF50F-1D4B-4423-9DB4-40AC5EC15923, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:3EA7603A-B4A7-48D8-B1B1-D53286986F79, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:F94FE808-E31D-407D-B6C1-59F74EE985B1, OS:15.0, name:iPod touch (7th generation) }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/mac/development/flutter253/.pub-cache/hosted/pub.dartlang.org/gt3_flutter_plugin-0.0.2/ios/Classes/Gt3FlutterPlugin.m:59:27: warning: 'configureGTest:challenge:success:withAPI2:' is deprecated: registerCaptchaWithCustomAsyncTask:completion: [-Wdeprecated-declarations]
                [self.manager configureGTest:geetest_id
                              ^
    In module 'GT3Captcha' imported from /Users/mac/development/flutter253/.pub-cache/hosted/pub.dartlang.org/gt3_flutter_plugin-0.0.2/ios/Classes/Gt3FlutterPlugin.h:2:
    /Users/mac/Project/captcha/ios/Pods/GT3Captcha-iOS/SDK/GT3Captcha.framework/Headers/GT3CaptchaManager.h:103:42: note: 'configureGTest:challenge:success:withAPI2:' has been explicitly marked deprecated here
                  withAPI2:(NSString *)api_2 DEPRECATED_MSG_ATTRIBUTE("registerCaptchaWithCustomAsyncTask:completion:");
                                             ^
    In module 'UIKit' imported from /Users/mac/Project/captcha/ios/Pods/Target Support Files/gt3_flutter_plugin/gt3_flutter_plugin-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk/usr/include/AvailabilityMacros.h:185:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Users/mac/development/flutter253/.pub-cache/hosted/pub.dartlang.org/gt3_flutter_plugin-0.0.2/ios/Classes/Gt3FlutterPlugin.m:59:27: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
                [self.manager configureGTest:geetest_id
                              ^
    2 warnings generated.
    2 warnings generated.
    ld: in /Users/mac/Project/captcha/ios/Pods/GT3Captcha-iOS/SDK/GT3Captcha.framework/GT3Captcha(GT3CaptchaManager.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    /Users/mac/Project/captcha/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'GT3Captcha-iOS' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12.
------------
flutter doctor -v
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)

• No issues found!
mac@Dinhs-MacBook-Pro-2 ~/P/c/ios> flutter253 doctor -v
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-VN)
    • Flutter version 2.5.3 at /Users/mac/development/flutter253
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 12 (mobile) • BA113F67-8A81-4494-A6FE-14CBE1AE690F • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 95.0.4638.69

• No issues found!

How can i resolve this error ?

Thanks

**Comment by NikoXu** [comment]
Please double check your project setting.
GeeTest Captcha don't support simulator with arm64.

https://stackoverflow.com/questions/69306519/flutter-error-xcodebuild-warning-using-the-first-of-multiple-matching-destina
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io

**Comment by NikoXu** [comment]
> Please double check your project setting. GeeTest Captcha don't support simulator with arm64.
> 
> https://stackoverflow.com/questions/69306519/flutter-error-xcodebuild-warning-using-the-first-of-multiple-matching-destina https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io

@TranVanDinh235

**Comment by dinhtran16** [comment]
@NikoXu 
Thanks for taking the time. I tried both but my app still won't run on IOS simulator. I switched to using a real device and the plugin worked fine.
