### ISSUE TITLE
error in android  ->"result" is null（solution）

### ISSUE THREAD

**Issue by Wellcomezhangheng** [GeeTeam/gt3_flutter_plugin#2]
override fun onDialogResult(result: String?) {
// json to map
          var resultMap = getMap(result)

// add this line
          channel.invokeMethod("onResult", mapOf("code" to "$captchaCode", "result" to resultMap))
          gt3GeetestUtils.showSuccessDialog()
        }

**Comment by ghost** [comment]
Hi, thank you for reporting. We will fix it in the source code ASAP.

**Comment by ghost** [comment]
Should be fixed in 61902698d36a1eadf7636d4243719e673580c683.
